### ISSUE TITLE
ram out of memory

### ISSUE THREAD

**Issue by robin087** [hugochan/Graph2Seq-for-KGQG#4]
When I use colab to run this project, I have met the problem of ram out of memory. This problem happens during the 30th to 40th epoch. When this problem happens, the training stops without raising exception and the model can not reach the test part.
Have you ever net this problem? And how can I solve it?

**Comment by hugochan** [comment]
@robin087 sorry for the late reply! I haven't encountered the OOM issue. What's your GPU memory size? Can you try reducing the batch size to save memory?
