### ISSUE TITLE
how to obtain the datasets?

### ISSUE THREAD

**Issue by zxgx** [hugochan/Graph2Seq-for-KGQG#5]
I notice that some scripts are provided in src/scripts, and they seem to be related to data preprocessing. 

Could you please explain how can I get your datasets from freebase and WebQuestionsSP/CWQ?

**Comment by hugochan** [comment]
> I notice that some scripts are provided in src/scripts, and they seem to be related to data preprocessing.
> 
> Could you please explain how can I get your datasets from freebase and WebQuestionsSP/CWQ?

@zxgx thank you for your interest to our work! The datasets used in this work were created by [1]. You will find more details on them from the paper.


[1] V. Kumar, Y. Hua, G. Ramakrishnan, G. Qi, L. Gao, and Y.-F. Li,
“Difficulty-controllable multi-hop question generation from knowledge graphs,” in International Semantic Web Conference. Springer, 2019, pp. 382–398.

**Comment by zxgx** [comment]
> > I notice that some scripts are provided in src/scripts, and they seem to be related to data preprocessing.
> > Could you please explain how can I get your datasets from freebase and WebQuestionsSP/CWQ?
> 
> @zxgx thank you for your interest to our work! The datasets used in this work were created by [1]. You will find more details on them from the paper.
> 
> [1] V. Kumar, Y. Hua, G. Ramakrishnan, G. Qi, L. Gao, and Y.-F. Li,
> “Difficulty-controllable multi-hop question generation from knowledge graphs,” in International Semantic Web Conference. Springer, 2019, pp. 382–398.

Thank you for your reply. 
I had already read this paper, but they don't even provide any explicit instruction to run their code: [mhqg](https://github.com/liyuanfang/mhqg)

I would very appreciate it if you could provide some instructions to generate the datasets~

**Comment by hugochan** [comment]
> > > I notice that some scripts are provided in src/scripts, and they seem to be related to data preprocessing.
> > > Could you please explain how can I get your datasets from freebase and WebQuestionsSP/CWQ?
> > 
> > 
> > @zxgx thank you for your interest to our work! The datasets used in this work were created by [1]. You will find more details on them from the paper.
> > [1] V. Kumar, Y. Hua, G. Ramakrishnan, G. Qi, L. Gao, and Y.-F. Li,
> > “Difficulty-controllable multi-hop question generation from knowledge graphs,” in International Semantic Web Conference. Springer, 2019, pp. 382–398.
> 
> Thank you for your reply.
> I had already read this paper, but they don't even provide any explicit instruction to run their code: [mhqg](https://github.com/liyuanfang/mhqg)
> 
> I would very appreciate it if you could provide some instructions to generate the datasets~

@zxgx You can find the PQ and WQ data in their repo (https://github.com/liyuanfang/mhqg/tree/master/final_data). The scripts provided in src/scripts of this repo can be used to preprocess the above raw data for running our model. Hope this answers your question.

**Comment by zxgx** [comment]
Thanks a lot !
