### ISSUE TITLE
Test Trained Model

### ISSUE THREAD

**Issue by Reham-Osama** [hugochan/Graph2Seq-for-KGQG#8]
Is there a way to test the trained model without performing the training again and evaluating the model?

I used the following command for training:
`python main.py -config config/mhqg-wq/graph2seq.yml`

Now I need to use this trained model to do some predictions on a new file, Is there a way to do that given the current code?

**Comment by hugochan** [comment]
@Reham-Osama sorry for the late response! Yes, you can achieve the goal by commenting out `model.train()` in the [main file](https://github.com/hugochan/Graph2Seq-for-KGQG/blob/master/src/main.py#L24).
